variable "project_id" { } 
variable "region" { }
variable "zone" { }
variable "key" { }
variable "machine_type" { }
variable "startup_script" { }
variable "DARLENE1_TOKEN" { }
variable "DARCANO_TOKEN" { }
variable "TELEGRAM_ID" { }
variable "COLD_DELEG_CERT" { }
variable "COLD_NODE_CERT" { }
variable "COLD_NODE_COUNTER" { }
variable "COLD_NODE_SKEY" { }
variable "COLD_NODE_VKEY" { }
variable "COLD_PAY_ADDR" { }
variable "COLD_PAY_SKEY" { }
variable "COLD_PAY_VKEY" { }
variable "COLD_POOL_CERT" { }
variable "COLD_STAKE_ADDR" { }
variable "COLD_STAKE_CERT" { }
variable "COLD_STAKE_SKEY" { }
variable "COLD_STAKE_VKEY" { }
variable "EVOLVING_SKEY" { }
variable "EVOLVING_VKEY" { }
variable "VRF_SKEY" { }
variable "VRF_VKEY" { }
variable "POOL_METADATA_HASH" { }