name: Init Cloud (GCP only)

on:
  push:
    branches:
      - terraforming

env:
  PROJECT_ID: theta-inkwell-326216
  GCLOUD_TF_BUCKET_NAME: darcano-terraform-state
  GCLOUD_PROJECT_REGION: us-central1
  GCLOUD_SA_KEY: ${{ secrets.GCLOUD_SA_KEY }}  
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true
        
    - name: Setup GCP
      run: |
        echo "Checking TF state bucket: ${GCLOUD_PROJECT_REGION}"
        gsutil ls gs://${GCLOUD_APP_BUCKET_NAME}
        if [[ "$?" -eq "0" ]]; then
          hasBucket=true
          echo ${hasBucket}
        else
          gsutil mb -l ${GCLOUD_PROJECT_REGION} -p ${PROJECT_ID} -c standard gs://${GCLOUD_TF_BUCKET_NAME}
          hasBucket=true
          echo ${hasBucket}
        fi       
        
  terraform:
    name: Terraform
    needs: setup
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: get commit message
      run: |
         echo ::set-env name=commit_msg::$(git log --format=%B -n 1 ${{ github.event.after }})
    
    - name: Create Dev
      if: "contains( env.commit_msg, '[terraform-plan]')"
      run: |
          terraform init
          
    - name: Shutdown Dev Box
      if: "contains( env.commit_msg, '[terraform-destroy]')"
      run: |
          terraform destroy --auto-approve
          
    - name: Prompt Message
      if: "! contains( env.commit_msg, '[terraform-apply]') && !contains( env.commit_msg, '[terraform-destroy]')"
      run: |
          echo "No terraform flag was detected to run functionalities..."
    
  verification:
    name: Verification
    needs: setup
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: get commit message
      run: |
        echo "---> ${commit_msg}"

