name: Init Cloud (GCP only)

on:
  push:
    branches:
      - terraforming

env:
  PROJECT_ID: theta-inkwell-326216
  GCLOUD_TF_BUCKET_NAME: darcano-terraform-state
  GCLOUD_PROJECT_REGION: us-central1
  GCLOUD_SA_KEY: ${{ secrets.GCLOUD_SA_KEY }}  
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true
        
    - name: Setup GCP
      run: |
        export
        #TODO: check if bucket already exists: https://docs.github.com/en/actions/learn-github-actions/environment-variables
        #gsutil mb -l ${GCLOUD_PROJECT_REGION} -p ${PROJECT_ID} -c standard gs://${GCLOUD_TF_BUCKET_NAME}
        
  terraform:
    name: Terraform
    needs: setup
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: get commit message
      run: |
         echo ::set-env name=commit_msg::$(git log --format=%B -n 1 ${{ github.event.after }})
    
    - name: Create Dev
      if: "contains( env.commit_msg, '[terraform-plan]')"
      run: |
          export
          cd cloud/terraform
          terraform init --backend-config="bucket=${GCLOUD_TF_BUCKET_NAME}" --backend-config="prefix=tf-state"
          terraform plan
          
    - name: Shutdown Dev Box
      if: "contains( env.commit_msg, '[terraform-destroy]')"
      run: |
          terraform destroy --auto-approve
          
    - name: Prompt Message
      if: "! contains( env.commit_msg, '[terraform-apply]') && !contains( env.commit_msg, '[terraform-destroy]')"
      run: |
          echo "No terraform flag was detected to run functionalities..."
