name: Init OCI

on:
  push:
    branches:
      - oci

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Setup OCI
      run: |
        echo "i am here"
        mkdir ~/.oci
        echo "[DEFAULT]" >> ~/.oci/config
        echo "user=${{secrets.OCI_USER_OCID}}" >> ~/.oci/config
        echo "fingerprint=${{secrets.OCI_FINGERPRINT}}" >> ~/.oci/config
        echo "pass_phrase=${{secrets.OCI_PASSPHRASE}}" >> ~/.oci/config
        echo "region=${{secrets.OCI_REGION}}" >> ~/.oci/config
        echo "tenancy=${{secrets.OCI_TENANCY_OCID}}" >> ~/.oci/config
        echo "key_file=~/.oci/key.pem" >> ~/.oci/config
        echo "${{secrets.OCI_KEY_FILE}}" >> ~/.oci/key.pem
