name: Init OCI

on:
  push:
    branches:
      - oci
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Setup OCI
      run: |
        echo "i am here"
        mkdir ~/.oci
        echo "[DEFAULT]" >> ~/.oci/config
        echo "user=${{secrets.OCI_USER_OCID}}" >> ~/.oci/config
        echo "fingerprint=${{secrets.OCI_FINGERPRINT}}" >> ~/.oci/config
        echo "pass_phrase=${{secrets.OCI_PASSPHRASE}}" >> ~/.oci/config
        echo "region=${{secrets.OCI_REGION}}" >> ~/.oci/config
        echo "tenancy=${{secrets.OCI_TENANCY_OCID}}" >> ~/.oci/config
        echo "key_file=~/.oci/key.pem" >> ~/.oci/config
        echo "${{secrets.OCI_KEY_FILE}}" >> ~/.oci/key.pem
        
    - name: Install OCI CLI
      run: |
        curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
        chmod +x install.sh
        ./install.sh --accept-all-defaults
        echo "i am here"
        ls -lrt /home/runner/lib/oracle-cli/bin/oci
        #echo "::add-path::/home/runner/bin"
        #exec -l $SHELL
        
    - name: Fix Config File Permissions
      run: |
        /home/runner/lib/oracle-cli/bin/oci setup repair-file-permissions --file /home/runner/.oci/config
        /home/runner/lib/oracle-cli/bin/oci setup repair-file-permissions --file /home/runner/.oci/key.pem
        
    - name: 'Check Existing Instance'
      run: |
        echo "::set-env name=INSTANCE_OCID::$( \
          /home/runner/lib/oracle-cli/bin/oci compute instance list \
          --lifecycle-state RUNNING \
          --compartment-id ${{secrets.VM_COMPARTMENT_OCID}} \
          --display-name cicd-demo \
          --query "data [0].id" \
          --raw-output \
        )"
    
    - name: 'Create Instance'
      if: ${{!env.INSTANCE_OCID}}
      run: |
        echo "::set-env name=INSTANCE_OCID::$( \
          /home/runner/lib/oracle-cli/bin/oci compute instance launch \
            --compartment-id ${{secrets.VM_COMPARTMENT_OCID}} \
            --availability-domain ${{secrets.VM_AVAILABILITY_DOMAIN}} \
            --shape ${{secrets.VM_SHAPE}} \
            --assign-public-ip true \
            --display-name cicd-demo \
            --image-id ${{secrets.VM_CUSTOM_IMAGE_OCID}} \
            --ssh-authorized-keys-file /home/runner/.oci/id_vm.pub \
            --subnet-id ${{secrets.VM_SUBNET_OCID}} \
            --wait-for-state RUNNING \
            --query "data.id" \
            --raw-output \
        )"
